const MONGO_URL = process.env.MONGO_URL;
const JWT_USER_PASSWORD = process.env.JWT_USER_PASSWORD;
const JWT_ADMIN_PASSWORD = process.env.JWT_ADMIN_PASSWORD;

module.exports = {
    MONGO_URL: MONGO_URL,
    JWT_USER_PASSWORD: JWT_USER_PASSWORD,
    JWT_ADMIN_PASSWORD: JWT_ADMIN_PASSWORD,
}
